version: "3"
services:
  mysql_container:
    image: mysql:8.1.0
    container_name: mysql
    ports:
      - "3308:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=guesstheprice
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=raonpark
      - MYSQL_PASSWORD=1234
    networks:
      - guesstheprice
    volumes:
      - ./db/mysql
    restart:
      always

  redis-master:
    image: bitnami/redis:7.2.2
    container_name: redis-master
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master
    volumes:
      - ./db/redis/data:/var/lib/redis
    restart:
      always
    networks:
      - guesstheprice

  redis-slave1:
    image: bitnami/redis:7.2.2
    container_name: redis-slave1
    ports:
      - "16379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
    volumes:
      - ./db/redis/data:/var/lib/redis
    restart:
      always
    networks:
      - guesstheprice
    depends_on:
      - redis-master
  redis-slave2:
    image: bitnami/redis:7.2.2
    container_name: redis-slave2
    ports:
      - "16380:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
    volumes:
      - ./db/redis/data:/var/lib/redis
    restart:
      always
    networks:
      - guesstheprice
    depends_on:
      - redis-master
      - redis-slave1

  redis-sentinel1:
    image: bitnami/redis-sentinel:7.2.2
    container_name: redis-sentinel1
    ports:
      - "26379:26379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=10000
      - REDIS_SENTINEL_QUORUM=2
      - REDIS_MASTER_SET=mymaster
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
    networks:
      - guesstheprice
  redis-sentinel2:
    image: bitnami/redis-sentinel:7.2.2
    container_name: redis-sentinel2
    ports:
      - "26380:26379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=10000
      - REDIS_SENTINEL_QUORUM=2
      - REDIS_MASTER_SET=mymaster
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
    networks:
      - guesstheprice
  redis-sentinel3:
    image: bitnami/redis-sentinel:7.2.2
    container_name: redis-sentinel3
    ports:
      - "26381:26379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=10000
      - REDIS_SENTINEL_QUORUM=2
      - REDIS_MASTER_SET=mymaster
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
    networks:
      - guesstheprice


networks:
  guesstheprice:
    driver: bridge