spring:
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/guesstheprice?serverTimezone=Asia/Seoul&useSSL=false
  security:
    user:
      password: 1
  data:
    redis:
      sentinel:
        master: redis-master
        nodes:
          - redis-sentinel1:26379
          - redis-sentinel2:26380
          - redis-sentinel3:26381
      lettuce:
        shutdown-timeout: 200ms
        pool:
          enabled: true